MangerSain/Models/Items.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MangerSain.Models
{
    public class Items
    {
        
        public int Id { get; set; }
        [Required(ErrorMessage = "Votre boisson doit avoir un nom.")]
        public string Nom { get; set; }

        [Display(Name ="Prix")]
        [Required(ErrorMessage = "Votre boisson doit avoir un prix.")]
        public decimal Prix { get; set; }

        [MaxLength(200, ErrorMessage ="Pas plus de 200 caractères.")]
        public  string Description { get; set; }



        //test
    }
}

MangerSain/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class ItemsController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Clients = db.Clients.ToList();

            return View(items);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(items);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(items);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Items items = db.Items.Find(id);
            db.Items.Remove(items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Controllers/LaitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class LaitsController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: Laits
        public ActionResult Index()
        {
            return View(db.Laits.ToList());
        }

        // GET: Laits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lait lait = db.Laits.Find(id);
            if (lait == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clients = db.Clients.ToList();

            return View(lait);
        }

        // GET: Laits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Laits/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description,MatièreGrasse,Volume")] Lait lait)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(lait);
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }

            return View(lait);
        }

        // GET: Laits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lait lait = db.Laits.Find(id);
            if (lait == null)
            {
                return HttpNotFound();
            }
            return View(lait);
        }

        // POST: Laits/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description,MatièreGrasse")] Lait lait)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lait).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }
            return View(lait);
        }

        // GET: Laits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lait lait = db.Laits.Find(id);
            if (lait == null)
            {
                return HttpNotFound();
            }
            return View(lait);
        }

        // POST: Laits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lait lait = db.Laits.Find(id);
            db.Items.Remove(lait);
            db.SaveChanges();
            return RedirectToAction("Index", "Items");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Controllers/LegumesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class LegumesController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: Legumes
        public ActionResult Index()
        {
            return View(db.Legumes.ToList());
        }

        // GET: Legumes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Legume legume = db.Legumes.Find(id);
            if (legume == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clients = db.Clients.ToList();

            return View(legume);
        }

        // GET: Legumes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Legumes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description,Provenance")] Legume legume)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(legume);
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }

            return View(legume);
        }

        // GET: Legumes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Legume legume = db.Legumes.Find(id);
            if (legume == null)
            {
                return HttpNotFound();
            }
            return View(legume);
        }

        // POST: Legumes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description,Provenance")] Legume legume)
        {
            if (ModelState.IsValid)
            {
                db.Entry(legume).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }
            return View(legume);
        }

        // GET: Legumes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Legume legume = db.Legumes.Find(id);
            if (legume == null)
            {
                return HttpNotFound();
            }
            return View(legume);
        }

        // POST: Legumes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Legume legume = db.Legumes.Find(id);
            db.Items.Remove(legume);
            db.SaveChanges();
            return RedirectToAction("Index", "Items");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Controllers/TheTisanesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class TheTisanesController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: TheTisanes
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: TheTisanes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTisane theTisane = db.TheTisanes.Find(id);
            if (theTisane == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clients = db.Clients.ToList();

            return View(theTisane);
        }

        // GET: TheTisanes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TheTisanes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description,Cafeine")] TheTisane theTisane)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(theTisane);
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }

            return View(theTisane);
        }

        // GET: TheTisanes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTisane theTisane = db.TheTisanes.Find(id);
            if (theTisane == null)
            {
                return HttpNotFound();
            }
            return View(theTisane);
        }

        // POST: TheTisanes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description,Cafeine")] TheTisane theTisane)
        {
            if (ModelState.IsValid)
            {
                db.Entry(theTisane).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }
            return View(theTisane);
        }

        // GET: TheTisanes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTisane theTisane = db.TheTisanes.Find(id);
            if (theTisane == null)
            {
                return HttpNotFound();
            }
            return View(theTisane);
        }

        // POST: TheTisanes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TheTisane theTisane = db.TheTisanes.Find(id);
            db.Items.Remove(theTisane);
            db.SaveChanges();
            return RedirectToAction("Index", "Items");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Views/Items/Create.cshtml
@model MangerSain.Models.Items

@{
    ViewBag.Title = "Créer";
}

<h2>Créer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
 
        <table class="table">
            <tbody>
                <tr>

                   
                    <td>
                        <div>
                            @Html.ActionLink("Jus", "Index","Jus", null, new { @class = " btn btn-success sizeButton " })
                        </div>
                    </td>
                    <td>
                        <div>
                            @Html.ActionLink("Lait", "Create", "Laits",null, new { @class = "btn btn-success sizeButton" })
                        </div>
                    </td>
                    <td>
                        <div>
                            @Html.ActionLink("Légumes", "Create","Legumes", null, new { @class = "btn btn-success sizeButton" })
                        </div>
                    </td>
                    <td>
                        <div>
                            @Html.ActionLink("Noix", "Create", "Noix", null, new { @class = "btn btn-success sizeButton" })
                        </div>
                    </td>
                    <td>
                        <div>
                            @Html.ActionLink("Thé & Tisane", "Create","TheTisanes", null, new { @class = "btn btn-success sizeButton " })
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

       


}


        <div>
            @Html.ActionLink("Retour à la liste", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

MangerSain/Views/Items/Delete.cshtml
@model MangerSain.Models.Items

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>êtes-vous sûr de vouloir supprimer @Html.DisplayFor(model => model.Nom) ?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la list", "Index")
        </div>
    }
</div>

MangerSain/Views/Items/Details.cshtml
@model MangerSain.Models.Items

@{

    ViewBag.Title = "Détails";
    SelectList SelectListClient = new SelectList(ViewBag.Clients, "Id","Prenom");

}

<h2>Détails</h2>

<div>
    <h4>
        @Html.DisplayFor(model => model.Nom)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retour à la Liste", "Index") |
    
    @using (Html.BeginForm("AjouterItem","Paniers",new { id = Model.Id },FormMethod.Post,null))
    {
        @Html.DropDownList("ListClient", SelectListClient,"sélectionner un client",new { @class = "form-control" })
        <button type="submit" class="btn btn-success">Ajouter dans panier</button>
    }
</p>

MangerSain/Views/Items/Edit.cshtml
@model MangerSain.Models.Items

@{
    ViewBag.Title = "Modifier";
}

<h2>Modifier</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MangerSain/Views/Items/Index.cshtml
@model IEnumerable<MangerSain.Models.Items>

@{
    ViewBag.Title = "Catalogue";
}

<h2>Catalogue</h2>

<p class="jumbotron">
    @Html.ActionLink("Créer Nouveau", "Create" , "Items", new { @class = "btn btn-default" }) si vous êtes un administrateur
</p>

<div class="row">
    @foreach (var annonce in Model)
    {
        string NomControlleur = annonce.GetType().Name;

        if (NomControlleur != "Noix" && NomControlleur != "Jus" && NomControlleur != "Boissons")
        {
            NomControlleur += "s";
        }
        <div class="col-xs-12 col-sm-6 col-md-3 p-1">
            <div class="border rounded p-2">
                <h4>@Html.ActionLink(NomControlleur, "Index", NomControlleur)</h4>
                <h5>@annonce.Nom <br /><span class="badge badge-primary">@(annonce.Prix.ToString() + '$')</span></h5>
                <p>@(annonce.Description ?? "Aucune description")</p>
                @Html.ActionLink("Détail", "Details", NomControlleur, new { id = annonce.Id }, new { @class = "btn btn-info" })
                @*@Html.ActionLink("Modifier", "Edit", NomControlleur, new { id = annonce.Id }, new { @class = "btn btn-primary" })*@

            </div>
        </div>
    }
</div>