MangerSain/Models/Noix.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MangerSain.Models
{
    public class Noix : Items
    {
        [Required(ErrorMessage = "Choisir le bon état")]
        [Display(Name ="Avec coquille?")]
        public TypeEtat Etat { get; set; }

        [Display(Name ="L'enrobage")]
        [Required(ErrorMessage = "Choisir l'enrobage")]
        public TypeCoquille Coquille { get; set; }
    }

    public enum TypeCoquille
    {
        avec,
        sans
    }
    public enum TypeEtat
    {
        grillé,
        nature,
        salé
    }

}

MangerSain/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class ItemsController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Clients = db.Clients.ToList();

            return View(items);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(items);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(items);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Items items = db.Items.Find(id);
            db.Items.Remove(items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Controllers/NoixController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class NoixController : Controller
    {
        private MangerSainContext db = new MangerSainContext();

        // GET: Noixes
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Noixes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noix noix = db.Noix.Find(id);
            if (noix == null)
            {
                return HttpNotFound();
            }

            ViewBag.Clients = db.Clients.ToList();

            return View(noix);
        }

        // GET: Noixes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Noixes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prix,Description,Etat,Coquille")] Noix noix)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(noix);
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }

            return View(noix);
        }

        // GET: Noixes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noix noix = db.Noix.Find(id);
            if (noix == null)
            {
                return HttpNotFound();
            }
            return View(noix);
        }

        // POST: Noixes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Prix,Description,Etat,Coquille")] Noix noix)
        {
            if (ModelState.IsValid)
            {
                db.Entry(noix).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Items");
            }
            return View(noix);
        }

        // GET: Noixes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noix noix = db.Noix.Find(id);
            if (noix == null)
            {
                return HttpNotFound();
            }
            return View(noix);
        }

        // POST: Noixes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Noix noix = db.Noix.Find(id);
            db.Items.Remove(noix);
            db.SaveChanges();
            return RedirectToAction("Index", "Items");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MangerSain.DAL;
using MangerSain.Models;

namespace MangerSain.Controllers
{
    public class PaniersController : Controller
    {
        public string NomClient;
        private MangerSainContext db = new MangerSainContext();

        // GET: Paniers
        public ActionResult Index([Bind(Include = "Nom,Prix")] Items items)
        {
            return View(db.Paniers.ToList());
        }

        // GET: Paniers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Paniers.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            ViewBag.Clients = db.Clients.ToList();
            return View(panier);
        }

        [HttpPost]
        public ActionResult AjouterItem(int id)
        {
            Items item = db.Items.Find(id);

            if (item == null)
            {
                return HttpNotFound();
            }

            string ListeClient = Request.Form.Get("ListClient");
            if (String.IsNullOrEmpty(ListeClient))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(int.Parse(ListeClient));
            if (client.PanierClient == null)
            {
                client.PanierClient = new Panier
                {
                    ListeItems = new List<PanierItem>()
                };
                db.Paniers.Add(client.PanierClient);
                db.SaveChanges();
            }
            PanierItem panierItem = client.PanierClient.ListeItems.Find(Pi => Pi.Article.Id == id);

            if (panierItem == null)
            {
                panierItem = new PanierItem
                {
                    Article = item,
                    Quantite = 1
                };
                client.PanierClient.ListeItems.Add(panierItem);
            }
            else
            {
                client.PanierClient.ListeItems.Find(Pi => Pi.Article.Id == id).Quantite++;
            }
            client.PanierClient.Total = 0;
            foreach (PanierItem element in client.PanierClient.ListeItems)
            {
                client.PanierClient.Total += element.Article.Prix * element.Quantite;
            }



            db.Entry(client.PanierClient).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { Id = client.PanierClient.Id });
        }

        public ActionResult AjouterItemPlus(int idItem, int idPanier, int quantiteModif)
        {


            Panier panier = db.Paniers.Find(idPanier);
           
            

            PanierItem panierItem =panier.ListeItems.Find(Pi => Pi.Id == idItem);

            if (panierItem == null)
            {

                return HttpNotFound();
            }
            if (panierItem.Quantite + quantiteModif <= 0)
            {
                return RedirectToAction("Details", new { Id = idPanier });
            }
            panierItem.Quantite += quantiteModif;
            panier.Total = 0;
            foreach (PanierItem element in panier.ListeItems)
            {
                panier.Total += element.Article.Prix * element.Quantite;
            }

            db.Entry(panier).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { Id = idPanier });
        }


        // GET: Paniers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Paniers/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ListeItems,Total")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Paniers.Add(panier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(panier);
        }

        // GET: Paniers/Edit/5
        public ActionResult Edit(int id)
        {
            string ListeClient = Request.Form.Get("ListClient");
            if (String.IsNullOrEmpty(ListeClient))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(int.Parse(ListeClient));
            //if (id == null)
            //{
            //  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            foreach (PanierItem element in client.PanierClient.ListeItems)
            {
                element.Quantite++;
            }
            //Panier panier = db.Paniers.Find(id);
            // if (panier == null)
            // {
            //  return HttpNotFound();
            //}
            return View();
        }

        // POST: Paniers/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Total")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(panier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(panier);
        }



        // GET: Paniers/Delete/5
        public ActionResult Delete(int idItem, int idPanier)
        {

            Panier panier = db.Paniers.Find(idPanier);

            PanierItem panierItem = panier.ListeItems.Find(Pi => Pi.Id == idItem);

            if (panierItem == null)
            {

                return HttpNotFound();
            }
          
            db.PanierItems.Remove(panierItem);
            db.SaveChanges();
            panier.Total = 0;
            foreach (PanierItem element in panier.ListeItems)
            {
                panier.Total += element.Article.Prix * element.Quantite;
            }


            db.Entry(panier).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { Id = idPanier });
        }


        public ActionResult AjoutQuantite(int? idPanier)
        {

            string a = "1";
            string ListeClient = Request.Form.Get("ListClient");
            Panier panier = db.Paniers.Find(idPanier);
            Client client = db.Clients.Find(int.Parse(a));



            foreach (PanierItem element in client.PanierClient.ListeItems)
            {
                if (1 == element.Id)
                    element.Quantite++;
            }

            db.SaveChanges();
            return View(panier);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MangerSain/Views/Noix/Create.cshtml
@model MangerSain.Models.Noix

@{
    ViewBag.Title = "Créer";
}

<h2>Créer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noix</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Etat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Etat, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Etat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coquille, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Coquille, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coquille, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la Liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MangerSain/Views/Noix/Delete.cshtml
@model MangerSain.Models.Noix

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>êtes-vous sûr de vouloir supprimer @Html.DisplayFor(model => model.Nom)? </h3>
<div>
    <h4>Noix</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Etat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coquille)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coquille)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

MangerSain/Views/Noix/Details.cshtml
@model MangerSain.Models.Noix

@{
    ViewBag.Title = "Détails";
    SelectList SelectListClient = new SelectList(ViewBag.Clients, "Id", "Prenom");
}

<h2>Détails</h2>

<div>
    <h4>Noix</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Etat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Etat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coquille)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coquille)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retour à la liste", "Index","Items")
    @using (Html.BeginForm("AjouterItem", "Paniers", new { id = Model.Id }, FormMethod.Post, null))
    {
        @Html.DropDownList("ListClient", SelectListClient, "sélectionner un client", new { @class = "form-control" })
        <button type="submit" class="btn btn-success">Ajouter dans panier</button>
    }
</p>

MangerSain/Views/Noix/Edit.cshtml
@model MangerSain.Models.Noix

@{
    ViewBag.Title = "Modifier";
}

<h2>Modifier</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noix</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Etat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Etat, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Etat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coquille, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Coquille, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coquille, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la Liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MangerSain/Views/Noix/Index.cshtml
@model IEnumerable<MangerSain.Models.Noix>

@{
    ViewBag.Title = "Catalogue";
}

<h2>Catalogue</h2>

<p>
    @Html.ActionLink("Créer Nouveau", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Etat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Coquille)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Etat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Coquille)
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Détails", "Details", new { id=item.Id }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>